// import { cookies } from 'next/headers';

export const metadata = {
  title: 'Cart',
  description: 'Generated by create next app',
};

export default async function CartPage() {
  /* const totalItemsInCart = (await cookies()).get('cookieAmount'); */
  return (
    <>
        <div className="xLarge">
        <h1>Cart Page</h1>
      </div>
      {/* <h4>In Shopping Cart: {totalItemsInCart.value} </h4> */}
    </>
  );
}
/*  change and connect cookie name to singleProduct.id

search for cookieAmount to change name more than 1 place uses this
*/
