export const metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};

export default function BlogPage() {
  return (
    <>
      <div className="xLarge">
        <h1>Blog Page</h1>
      </div>
      <div className="container">
        <div style={{ display: 'grid', margin: '15px' }} className="large">
          <h4>"Brewing Memories: My Coffee Journey"</h4>
          <p>
            I’ll share anecdotes from my favorite coffee moments, from the cozy
            café where I first discovered the joys of pour-over brewing to the
            local roaster that taught me the nuances of bean selection. Each
            story will transport you to the places and experiences that have
            shaped my appreciation for this beloved drink.
          </p>
        </div>
        <div style={{ display: 'flex' }} className="small">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>
        <div className="xSmall">
          Profile
          <div className="profilePic">Pic</div>
        </div>
        <div className="long">
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris. Nisi ut
          aliquip ex ea commodo consequat."
        </div>
        <div className="xSmall">
          Profile
          <div className="profilePic">Pic</div>
        </div>
        <div className="long">
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris. Nisi ut
          aliquip ex ea commodo consequat."
        </div>
        <div className="xSmall">
          Profile
          <div className="profilePic">Pic</div>
        </div>
        <div className="long">
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris. Nisi ut
          aliquip ex ea commodo consequat."
        </div>
      </div>
    </>
  );
}
