export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

export default function AboutPage() {
  return (
    <div className="xLarge">
      <h1>About Page</h1>
    </div>
  );
}
