import Image from 'next/image';

export const metadata = {
  title: 'Category',
  description: 'Generated by create next app',
};

export default function CategoryPage() {
  return (
    <>
      <div className="xLarge">
        <h1>Category Page</h1>
      </div>
      <div className="container">
        <div className="small" style={{ display: 'flex' }}>
          <Image
            src="/images/illy espresso classic roast 250g.jpg"
            alt="illy espresso classic roast 250g"
            width={200}
            height={250}
          />
          <h2>Coffee Beans</h2>
        </div>

        <div
          className="large"
          style={{
            fontSize: '20px',
          }}
        >
          Coffee beans are the seeds of the coffee plant, found inside the fruit
          known as a coffee cherry. These beans are the primary ingredient in
          producing coffee, one of the most popular beverages worldwide. Here’s
          a more detailed description of coffee beans
        </div>

        <div
          className="large"
          style={{
            fontSize: '20px',
          }}
        >
          Coffee brewers are essential appliances for any coffee lover, designed
          to extract the rich flavors and aromas from coffee grounds to create
          the perfect cup of coffee. The brewing process can vary widely
          depending on the type of brewer, each offering unique characteristics
          that cater to different preferences and brewing styles.
        </div>

        <div className="small" style={{ display: 'flex' }}>
          <Image
            src="/images/hario coffee syphon technica 3cup.jpg"
            alt="hario coffee syphon technica 3cup"
            width={200}
            height={250}
          />
          <h2>Coffee Brewers</h2>
        </div>
        <div className="small" style={{ display: 'flex' }}>
          <Image
            src="/images/motta milk jug.jpg"
            alt="motta milk jug"
            width={200}
            height={250}
          />
          <h2>Coffee Accessory</h2>
        </div>

        <div
          className="large"
          style={{
            fontSize: '20px',
          }}
        >
          Coffee accessories are essential tools and gadgets designed to elevate
          your coffee brewing experience, ensuring that each cup is crafted to
          perfection. From grinders and scales to milk frothers and storage
          containers, the right accessories can significantly enhance the flavor
          and aroma of your coffee, making your daily ritual even more
          enjoyable.
        </div>

        <div
          className="large"
          style={{
            fontSize: '20px',
          }}
        >
          Coffee hand grinders are compact, manual devices designed to grind
          whole coffee beans into a desired consistency. They are favored by
          many coffee enthusiasts for their ability to produce fresh coffee
          grounds while allowing for greater control over the grinding process.
          Unlike electric grinders, hand grinders operate without the noise and
          energy consumption, making them an excellent choice for those who
          appreciate the art of coffee brewing.
        </div>

        <div className="small" style={{ display: 'flex' }}>
          <Image
            src="/images/rhinowares hand grinder adapter.jpg"
            alt="rhinowares hand grinder adapter"
            width={200}
            height={250}
          />
          <h2>Coffee Grinders</h2>
        </div>
      </div>
    </>
  );
}
