import Image from 'next/image';
import { getProducts } from './database/productlist';

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

export default function ProductPage() {
  const products = getProducts();
  return (
    <div>
      <h1>Product Page</h1>
      {products.map((product) => {
        return (
          <div key={`products-${product.id}`}>
            <div>{product.productName}</div>
            <Image
              src={`/images/${product.productName.toLowerCase()}.jpg`}
              alt={product.productName}
              width={200}
              height={250}
            />
          </div>
        );
      })}
    </div>
  );
}
