import Image from 'next/image';

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

const products = [
  {
    id: 1,
    productName: 'illy espresso classic roast 250g',
    categoryType: 'coffeeBeans',
    price: 9.99,
  },
  {
    id: 2,
    productName: 'murnauer san pedro bio honduras 250g',
    categoryType: 'coffeeBeans',
    price: 12.49,
  },
  {
    id: 3,
    productName: 'schwarzmond pluto 250g',
    categoryType: 'coffeeBeans',
    price: 8.99,
  },
  {
    id: 4,
    productName: 'gimoka granbar beans 1kg',
    categoryType: 'coffeeBeans',
    price: 18.99,
  },
  {
    id: 5,
    productName: 'fortezza espresso puro 250g',
    categoryType: 'coffeeBeans',
    price: 10.5,
  },
  {
    id: 6,
    productName: 'ohavn espresso staerk 1kg',
    categoryType: 'coffeeBeans',
    price: 21.99,
  },
  {
    id: 7,
    productName: 'supremo turron 250g',
    categoryType: 'coffeeBeans',
    price: 11.75,
  },
  {
    id: 8,
    productName: 'yocomo kickstarter 250g',
    categoryType: 'coffeeBeans',
    price: 10.99,
  },
  {
    id: 9,
    productName: 'dinzler espresso dark roast 250g',
    categoryType: 'coffeeBeans',
    price: 12.99,
  },
  {
    id: 10,
    productName: 'wittmann bar classico 250g',
    categoryType: 'coffeeBeans',
    price: 13.49,
  },
  {
    id: 11,
    productName: 'speicherstadt caffe crema beans 250g',
    categoryType: 'coffeeBeans',
    price: 11.99,
  },
  {
    id: 12,
    productName: 'mocambo brasilia beans 1kg',
    categoryType: 'coffeeBeans',
    price: 19.99,
  },
  {
    id: 13,
    productName: 'andraschko deja vu 250g',
    categoryType: 'coffeeBeans',
    price: 10.25,
  },
  {
    id: 14,
    productName: 'gorilla bar crema beans 1kg',
    categoryType: 'coffeeBeans',
    price: 22.5,
  },
  {
    id: 15,
    productName: 'gorilla superbar crema beans 1kg',
    categoryType: 'coffeeBeans',
    price: 23.5,
  },
  {
    id: 16,
    productName: 'hario coffee syphon technica 3cup',
    categoryType: 'brewer',
    price: 45.99,
  },
  {
    id: 17,
    productName: 'dripster brewjar 1.0L',
    categoryType: 'brewer',
    price: 29.99,
  },
  {
    id: 18,
    productName: 'bialetti espresso venus 2cup',
    categoryType: 'brewer',
    price: 39.5,
  },
  {
    id: 19,
    productName: 'chemex caraffe 6cup',
    categoryType: 'brewer',
    price: 42.99,
  },
  {
    id: 20,
    productName: 'hario clear coffee dripper',
    categoryType: 'brewer',
    price: 25.75,
  },
  {
    id: 21,
    productName: 'aeropress set',
    categoryType: 'brewer',
    price: 35.0,
  },
];
export default function ProductPage() {
  return (
    <div>
      <h1>Product Page</h1>
      {products.map((product) => {
        return (
          <div key={`products-${product.id}`}>
            <div>{product.productName}</div>
            <Image
              src={`/images/${product.productName.toLowerCase()}.jpg`}
              alt={product.productName}
              width={200}
              height={250}
            />
          </div>
        );
      })}
    </div>
  );
}
